include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields

analyzer:
  exclude:
    - build/**
    - lib/generated_plugin_registrant.dart